"""capture full plan schema for future ranking (offers, student, geo, data/network detail)

Revision ID: 4cc70fd66fa2
Revises: b5083e8e3079
Create Date: 2026-09-06 17:25:43.743522
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4cc70fd66fa2'
down_revision: str | None = 'b5083e8e3079'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('promo_savings_cad', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('promo_starts_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('promo_ends_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('promo_expiry_known', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('promo_duration_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('promo_new_customers_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('promo_online_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('promo_autopay_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('promo_source_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('activation_fee_waived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contract_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contract_length_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('byod_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_full_speed_gb', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('data_unlimited_is_full_speed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_hard_cap', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('overage_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('overage_rate_per_gb_cad', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('network_technology', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('max_download_mbps', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('includes_us', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('includes_mexico', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('us_mex_data_gb', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('international_roaming', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hotspot_data_gb', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hotspot_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('student_plan', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('student_offer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('student_eligibility_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('available_regions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('geo_availability_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('geo_availability_note')
        batch_op.drop_column('available_regions')
        batch_op.drop_column('student_eligibility_note')
        batch_op.drop_column('student_offer')
        batch_op.drop_column('student_plan')
        batch_op.drop_column('hotspot_note')
        batch_op.drop_column('hotspot_data_gb')
        batch_op.drop_column('international_roaming')
        batch_op.drop_column('us_mex_data_gb')
        batch_op.drop_column('includes_mexico')
        batch_op.drop_column('includes_us')
        batch_op.drop_column('max_download_mbps')
        batch_op.drop_column('network_technology')
        batch_op.drop_column('overage_rate_per_gb_cad')
        batch_op.drop_column('overage_note')
        batch_op.drop_column('data_hard_cap')
        batch_op.drop_column('data_unlimited_is_full_speed')
        batch_op.drop_column('data_full_speed_gb')
        batch_op.drop_column('byod_required')
        batch_op.drop_column('contract_note')
        batch_op.drop_column('contract_length_months')
        batch_op.drop_column('contract_required')
        batch_op.drop_column('activation_fee_waived')
        batch_op.drop_column('promo_source_url')
        batch_op.drop_column('promo_autopay_required')
        batch_op.drop_column('promo_online_only')
        batch_op.drop_column('promo_new_customers_only')
        batch_op.drop_column('promo_duration_months')
        batch_op.drop_column('promo_expiry_known')
        batch_op.drop_column('promo_ends_at')
        batch_op.drop_column('promo_starts_at')
        batch_op.drop_column('promo_savings_cad')
        batch_op.drop_column('promo_name')

    # ### end Alembic commands ###
