"""initial schema

Revision ID: 896b8239e48d
Revises: 
Create Date: 2026-09-02 23:29:06.546208
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '896b8239e48d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('network', sa.String(length=64), nullable=True),
    sa.Column('plan_model', sa.String(length=16), nullable=True),
    sa.Column('homepage_url', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_slug', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_slug'], ['providers.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_slug', 'url', name='uq_source_provider_url')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_provider_slug'), ['provider_slug'], unique=False)

    op.create_table('raw_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('retrieval', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_documents_source_id'), ['source_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_slug', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('plan_name', sa.String(length=256), nullable=True),
    sa.Column('plan_local_name', sa.String(length=256), nullable=True),
    sa.Column('price_cad', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price_period', sa.String(length=16), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('monthly_price_cad', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('regular_price_cad', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('promo_price_cad', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('promo_conditions', sa.Text(), nullable=True),
    sa.Column('activation_fee_cad', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('activation_note', sa.Text(), nullable=True),
    sa.Column('data_base_gb', sa.Float(), nullable=True),
    sa.Column('data_bonus_gb', sa.Float(), nullable=True),
    sa.Column('data_promo_gb', sa.Float(), nullable=True),
    sa.Column('data_total_gb', sa.Float(), nullable=True),
    sa.Column('data_unlimited', sa.Boolean(), nullable=True),
    sa.Column('throttled_after_note', sa.Text(), nullable=True),
    sa.Column('throttle_speed', sa.String(length=64), nullable=True),
    sa.Column('network_speed_tier', sa.String(length=128), nullable=True),
    sa.Column('has_5g', sa.Boolean(), nullable=True),
    sa.Column('plan_type', sa.String(length=16), nullable=True),
    sa.Column('canada_wide_calling', sa.Boolean(), nullable=True),
    sa.Column('unlimited_text', sa.Boolean(), nullable=True),
    sa.Column('international_text', sa.Boolean(), nullable=True),
    sa.Column('can_us_mex_note', sa.Text(), nullable=True),
    sa.Column('hotspot', sa.Boolean(), nullable=True),
    sa.Column('esim', sa.Boolean(), nullable=True),
    sa.Column('wifi_calling', sa.Boolean(), nullable=True),
    sa.Column('data_rollover', sa.Boolean(), nullable=True),
    sa.Column('autopay_required', sa.Boolean(), nullable=True),
    sa.Column('autopay_note', sa.Text(), nullable=True),
    sa.Column('byod', sa.Boolean(), nullable=True),
    sa.Column('device_restrictions', sa.Text(), nullable=True),
    sa.Column('international_roaming_note', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('availability', sa.String(length=64), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_rankable', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_slug'], ['providers.slug'], ),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_slug', 'external_id', name='uq_plan_provider_external')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_provider_slug'), ['provider_slug'], unique=False)

    op.create_table('refresh_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_slug', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('raw_document_id', sa.Integer(), nullable=True),
    sa.Column('retrieval', sa.String(length=16), nullable=True),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('plans_upserted', sa.Integer(), nullable=False),
    sa.Column('plans_valid', sa.Integer(), nullable=False),
    sa.Column('plans_flagged', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_runs_provider_slug'), ['provider_slug'], unique=False)

    op.create_table('plan_validation_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('refresh_run_id', sa.Integer(), nullable=True),
    sa.Column('provider_slug', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['refresh_run_id'], ['refresh_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_validation_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_validation_issues_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_validation_issues_provider_slug'), ['provider_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_validation_issues_refresh_run_id'), ['refresh_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_validation_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_validation_issues_refresh_run_id'))
        batch_op.drop_index(batch_op.f('ix_plan_validation_issues_provider_slug'))
        batch_op.drop_index(batch_op.f('ix_plan_validation_issues_plan_id'))

    op.drop_table('plan_validation_issues')
    with op.batch_alter_table('refresh_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_runs_provider_slug'))

    op.drop_table('refresh_runs')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_provider_slug'))

    op.drop_table('plans')
    with op.batch_alter_table('raw_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_raw_documents_content_hash'))

    op.drop_table('raw_documents')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_provider_slug'))

    op.drop_table('sources')
    op.drop_table('providers')
    # ### end Alembic commands ###
