"""pricing tiers (autopay/bundle/promo separate) + unlimited-data normalization

Revision ID: b0a9a6beed72
Revises: 4cc70fd66fa2
Create Date: 2026-09-06 21:54:32.061494
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b0a9a6beed72'
down_revision: str | None = '4cc70fd66fa2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autopay_price_cad', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('autopay_discount_cad', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('autopay_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bundle_price_cad', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('bundle_discount_cad', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('bundle_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('promo_stacks_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pricing_notes', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('pricing_notes')
        batch_op.drop_column('promo_stacks_conditions')
        batch_op.drop_column('bundle_conditions')
        batch_op.drop_column('bundle_discount_cad')
        batch_op.drop_column('bundle_price_cad')
        batch_op.drop_column('autopay_conditions')
        batch_op.drop_column('autopay_discount_cad')
        batch_op.drop_column('autopay_price_cad')

    # ### end Alembic commands ###
