"""source modes: manual + secondary + verification history

Revision ID: b5083e8e3079
Revises: 896b8239e48d
Create Date: 2026-09-03 10:26:58.270460
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b5083e8e3079'
down_revision: str | None = '896b8239e48d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_verification_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('provider_slug', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_kind', sa.String(length=32), nullable=False),
    sa.Column('source_mode', sa.String(length=24), nullable=False),
    sa.Column('verification_method', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_rankable', sa.Boolean(), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=True),
    sa.Column('raw_document_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('price_cad', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_verification_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_verification_events_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_verification_events_provider_slug'), ['provider_slug'], unique=False)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_mode', sa.String(length=24), server_default='official_automated', nullable=False))
        batch_op.add_column(sa.Column('verification_method', sa.String(length=32), server_default='automated_fetch', nullable=False))
        batch_op.add_column(sa.Column('verified_by', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('official_crosscheck', sa.Boolean(), server_default='0', nullable=False))
        batch_op.alter_column('verification_status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=24),
               existing_nullable=False)

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_source_mode', sa.String(length=24), nullable=True))

    with op.batch_alter_table('raw_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('official_source_url', sa.String(length=512), nullable=True))

    with op.batch_alter_table('refresh_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_mode', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('operator', sa.String(length=128), nullable=True))

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_mode', sa.String(length=24), server_default='official_automated', nullable=False))

    # ### end Alembic commands ###

    # --- data backfill: existing rows predate source modes -------------------
    # New Plan/Source columns already default to official_automated / automated_fetch
    # via server_default. Backfill the nullable provenance columns + seed one
    # verification-history row per existing plan from its current state.
    conn = op.get_bind()
    conn.execute(sa.text(
        "UPDATE providers SET default_source_mode = 'official_automated' "
        "WHERE default_source_mode IS NULL"
    ))
    conn.execute(sa.text(
        "UPDATE refresh_runs SET source_mode = 'official_automated' WHERE source_mode IS NULL"
    ))
    conn.execute(sa.text(
        """
        INSERT INTO plan_verification_events
            (plan_id, provider_slug, external_id, event_at, event_kind, source_mode,
             verification_method, verification_status, confidence, is_rankable,
             raw_document_id, source_url, content_hash, price_cad, note)
        SELECT id, provider_slug, external_id, last_verified_at, 'backfill',
               'official_automated', 'automated_fetch', verification_status, confidence,
               is_rankable, raw_document_id, source_url, content_hash, price_cad,
               'seeded from plan state at migration b5083e8e3079'
        FROM plans
        """
    ))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_column('source_mode')

    with op.batch_alter_table('refresh_runs', schema=None) as batch_op:
        batch_op.drop_column('operator')
        batch_op.drop_column('source_mode')

    with op.batch_alter_table('raw_documents', schema=None) as batch_op:
        batch_op.drop_column('official_source_url')
        batch_op.drop_column('captured_at')
        batch_op.drop_column('operator')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('default_source_mode')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('official_crosscheck')
        batch_op.drop_column('verified_by')
        batch_op.drop_column('verification_method')
        batch_op.drop_column('source_mode')

    with op.batch_alter_table('plan_verification_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_verification_events_provider_slug'))
        batch_op.drop_index(batch_op.f('ix_plan_verification_events_plan_id'))

    op.drop_table('plan_verification_events')
    # ### end Alembic commands ###
