import { useEffect, useRef } from 'react'

interface Props {
  onClose: () => void
}

/**
 * A lightweight explainer dialog. Plain language only — no equations, no
 * internal variable names.
 */
export function HowRankingsWork({ onClose }: Props) {
  const closeRef = useRef<HTMLButtonElement>(null)

  useEffect(() => {
    closeRef.current?.focus()
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', onKey)
    return () => document.removeEventListener('keydown', onKey)
  }, [onClose])

  return (
    <div
      className="hrw-overlay"
      onClick={onClose}
      role="presentation"
    >
      <div
        className="hrw-panel"
        role="dialog"
        aria-modal="true"
        aria-labelledby="hrw-title"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="hrw-head">
          <h2 id="hrw-title" className="hrw-title">How rankings work</h2>
          <button
            ref={closeRef}
            type="button"
            className="hrw-close"
            onClick={onClose}
            aria-label="Close"
          >
            &times;
          </button>
        </div>

        <div className="hrw-body">
          <p>
            Plans are scored using verified carrier data across{' '}
            <strong>Price</strong>, <strong>Data</strong>,{' '}
            <strong>Technology</strong>, <strong>Features</strong>,{' '}
            <strong>Roaming</strong> and <strong>Current Offers</strong>. The
            ranking mode you pick changes how much each of those matters — for
            example, “Cheapest” looks only at price, while “Most Data” looks only
            at full-speed data.
          </p>
          <ul>
            <li>
              The ranking is <strong>deterministic</strong> — the same data
              always produces the same order. It is not generated by AI.
            </li>
            <li>
              A conditional discount (AutoPay, a bundle, a student rate) is only
              treated as your price once you’ve confirmed you can meet that
              condition. Otherwise the regular price is used, and the discount is
              shown as secondary information.
            </li>
            <li>
              Annual plans are compared by their monthly-equivalent cost, but the
              full upfront payment is always shown on the card.
            </li>
            <li>
              Vancouver, Burnaby and Surrey currently share the same results —
              there is no made-up, area-specific network scoring.
            </li>
          </ul>
          <p className="hrw-foot">
            Every ranked plan shows a plain-language “Why this ranks here”
            explanation and a link to the carrier’s official page.
          </p>
        </div>
      </div>
    </div>
  )
}
